// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSqFvwaBtL7trasV0EbniBZGWzgB41_tY',
    appId: '1:424647601674:web:65c706da6313e034f0b9f3',
    messagingSenderId: '424647601674',
    projectId: 'ishare-app-d47b5',
    authDomain: 'ishare-app-d47b5.firebaseapp.com',
    storageBucket: 'ishare-app-d47b5.firebasestorage.app',
    measurementId: 'G-6PP9GEG0GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhRVnvJr5hqE707ah8gkpUGS2gQ034LIA',
    appId: '1:424647601674:android:2e959ad365a5cc90f0b9f3',
    messagingSenderId: '424647601674',
    projectId: 'ishare-app-d47b5',
    storageBucket: 'ishare-app-d47b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_E93o5m3mxPWVPpEdV1c-Nz-0VwCtXd0',
    appId: '1:424647601674:ios:83096c485ab4d75ef0b9f3',
    messagingSenderId: '424647601674',
    projectId: 'ishare-app-d47b5',
    storageBucket: 'ishare-app-d47b5.firebasestorage.app',
    iosBundleId: 'com.example.ishareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_E93o5m3mxPWVPpEdV1c-Nz-0VwCtXd0',
    appId: '1:424647601674:ios:83096c485ab4d75ef0b9f3',
    messagingSenderId: '424647601674',
    projectId: 'ishare-app-d47b5',
    storageBucket: 'ishare-app-d47b5.firebasestorage.app',
    iosBundleId: 'com.example.ishareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSqFvwaBtL7trasV0EbniBZGWzgB41_tY',
    appId: '1:424647601674:web:246106af73cd3444f0b9f3',
    messagingSenderId: '424647601674',
    projectId: 'ishare-app-d47b5',
    authDomain: 'ishare-app-d47b5.firebaseapp.com',
    storageBucket: 'ishare-app-d47b5.firebasestorage.app',
    measurementId: 'G-8N87JTCP5H',
  );
}
