# Generated by Django 5.2.8 on 2026-01-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_pics/'),
        ),
    ]
