# Generated by Django 5.2.8 on 2025-11-20 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverVerification',
        ),
    ]
