# Generated by Django 5.2.8 on 2025-11-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_driververification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos/'),
        ),
    ]
