# Generated by Django 5.2.8 on 2025-12-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_vehicle_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-created_at']},
        ),
    ]
