# Generated by Django 5.2.8 on 2025-12-14 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_trip_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='vehicle_plate_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Plate must be in Rwandan format (e.g., RAD 123 A)', regex='^R[A-Z]{2} \\d{3} [A-Z]$')]),
        ),
    ]
