# Generated by Django 5.2.8 on 2025-12-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userprofile_vehicle_plate_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
