# Generated by Django 5.2.8 on 2025-12-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile_reset_code_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='allows_luggage',
            field=models.BooleanField(default=False, verbose_name='Large Luggage Allowed'),
        ),
        migrations.AddField(
            model_name='trip',
            name='has_ac',
            field=models.BooleanField(default=False, verbose_name='Air Conditioning'),
        ),
        migrations.AddField(
            model_name='trip',
            name='has_music',
            field=models.BooleanField(default=False, verbose_name='Music Available'),
        ),
        migrations.AddField(
            model_name='trip',
            name='no_smoking',
            field=models.BooleanField(default=True, verbose_name='No Smoking'),
        ),
    ]
