# Generated by Django 5.2.8 on 2025-12-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_trip_allows_luggage_trip_has_ac_trip_has_music_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driververification',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='verification/'),
        ),
        migrations.AddField(
            model_name='driververification',
            name='national_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='verification/'),
        ),
    ]
