# Generated by Django 5.2.8 on 2026-01-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='target_role',
            field=models.CharField(choices=[('driver', 'Driver'), ('passenger', 'Passenger'), ('all', 'All Users')], default='all', help_text='Who can see this plan?', max_length=20),
        ),
    ]
